### ISSUE TITLE
Unexpected behavior when evaluating similar strings with .containDeep()

### ISSUE THREAD

**Issue by aaunel** [shouldjs/should.js#55]
Replication steps

```
// fails
['code-for-days', 'code'].should.containDeep(['code', 'code-for-days'])

// passes
['code-for-days', 'code-fast'].should.containDeep(['code-fast', 'code-for-days'])

// also passes (ordered)
['code', 'code-for-days'].should.containDeep(['code', 'code-for-days'])
```

Incorrect assertion is made when similar strings are tested using this method.

It appears to me that `.containDeep()` is traversing strings as arrays (e.g. `'foo'[0] === 'f'`) and asserting as if these are nested arrays.

**Comment by btd** [comment]
Yes looks like a bug. I will take a look at Friday I am on vacation now and do not have PC near me.

**Comment by btd** [comment]
I found the reason, because .containDeep search in strings with .indexOf and exclude first found strings.
So in first case it take 'code-for-days'.indexOf('code') >= 0 so it will take next 'code'.indexOf('code-for-days') which will not be found. So i think simply drop .indexOf to be .equal (===). As a best matched search will be overcompicated for this task.
Thoughts?
