### ISSUE TITLE
Chai-like "expect" API

### ISSUE THREAD

**Issue by bajtos** [shouldjs/should.js#60]
I am pondering the idea of moving from "chai" to "should.js", mostly because "should.js" has more assertions and supports `to.be.true()` function calls.

However, I really dislike `actual.should...` syntax, as it reports ugly failure messages when `actual` happens to be null or undefined.

Would you accept a pull request adding a new API "expect"? 

```js
var should = require('should');
var expect = should.expect;
expect(actual).to.equal(10); 
// initialise Assertion instance with obj=10 and call the "equal" checker
```

**Comment by btd** [comment]
Hello.
In should.js very actively used getters like you mentioned (`to.be.true` <- without brackets, see http://shouldjs.github.io/#assertion-true).
About `expect`, pls take a look on my example in [FAQ](https://github.com/shouldjs/should.js/wiki/FAQ#confusing-names). For full `expect` like behaviour need also call .noConflict() - it will restore Object.prototype to its initial state.

**Comment by bajtos** [comment]
> About expect, pls take a look on my example in FAQ.

Sweet, I did not realise there is this option. Can I also provide a custom "message" that way?

```js
should(actual, 'my message').equal(10);
```

I guess this issue can be closed then.

> In should.js very actively used getters like you mentioned (to.be.true <- without brackets, see http://shouldjs.github.io/#assertion-true).

Is there any particular reason why matchers like `true` cannot provide a function-based interface too? 
Chai used to support that (https://github.com/chaijs/chai/pull/297), but they have reverted it back.

See this [link] why property-getter matchers are a bad thing (setting aside the fact that most linters complain about their usage too).

**Comment by bajtos** [comment]
> About expect, pls take a look on my example in FAQ.

Sweet, I did not realise there is this option. Can I also provide a custom "message" that way?

```js
should(actual, 'my message').equal(10);
```

I guess this issue can be closed then.

> In should.js very actively used getters like you mentioned (to.be.true <- without brackets, see http://shouldjs.github.io/#assertion-true).

Is there any particular reason why matchers like `true` cannot provide a function-based interface too? 
Chai used to support that (https://github.com/chaijs/chai/pull/297), but they have reverted it back.

See this [link](https://github.com/moll/js-must#asserting-on-property-access) why property-getter matchers are a bad thing (setting aside the fact that most linters complain about their usage too).

**Comment by btd** [comment]
I would say i agree about getters assertions, but that was done even before i took should.js for maintaining (original work was done by tj holovaichuk). It will be huge breaking change.
About chaijs support of both .getter and .func() styles calls - i dislike how it is done (iirc they did it because of jshint violations - not because .getter can result a false positive). 
.getter return noop function, that just called to be look like it is function. In this case you expect your code will be executed when you type (), but it is executed much earlier. I will never do such things in should.js - all results should be expectable and predictable.
About link you mentioned i know about that possible disadvantage. For this purpose if platform support es6 proxy, all results will be protected by proxied value which will check if actual getter exists and assert if not. E.g you can try example with firefox.

> Sweet, I did not realise there is this option. Can I also provide a custom "message" that way?

Sorry no, custom messages in this way not supported. Only several assertions support additional messages.

**Comment by bajtos** [comment]
Thanks for explaining it all to me. I think should.js is not the right replacement for chai for me (or at least not now), I'll look into other options.

**Comment by btd** [comment]
Ok. Feel free to open issue, if you have any questions.
